package com.pennywiseai.shared.domain.mapping

object SharedCategoryMapping {

    // --- helpers ---
    private fun matches(
        merchantRaw: String,
        anyOf: Set<String>,
        noneOf: Set<String> = emptySet()
    ): Boolean {
        val m = merchantRaw.lowercase()
        if (noneOf.any { m.contains(it) }) return false

        return anyOf.any { keyword ->
            if (!keyword.contains(" ")) {
                val regex = "\\b${keyword.replace(".", "\\.")}\\b".toRegex()
                regex.containsMatchIn(m)
            } else {
                m.contains(keyword)
            }
        }
    }

    // --- keyword sets (single source of truth) ---
    private val FOOD = setOf(
        "swiggy",
        "zomato",
        "dominos",
        "pizza",
        "burger",
        "kfc",
        "mcdonalds",
        "restaurant",
        "cafe",
        "food",
        "starbucks",
        "haldiram",
        "barbeque",
        "foodpanda thailand",
        "linepay",
        "arabica",
        "chatramue",
        "after you",
        "kyo roll en",
        "roast",
        "al saray",
        "oh my juice",
        "careem food",
        "careem dineout",
        "deliveroo",
        "talabat",
        "peets",
        "safadi",
        "gazebo",
        "al baik",
        "jollibee",
        "raising canes",
        "chipotle",
        "kitopi",
        "sangeetha",
        "maharaja bhog",
        "al beiruti",
        "malabar tiffin house",
        "calicut paragon",
        "bikanervala",
        "karak house",
        "puranmal",
        "chicking",
        "papa johns",
        "phosphorus",
        "rang indian",
        "moishi",
        "cravings",
        "the matcha tokyo",
        "shawarma emprator",
        "shawrma alemprator",
        "tabaq alhejazi",
        "mehfil biriyani",
        "desert shawarma",
        "mr tea",
        "papparoti",
        "samak alhejazi",
        "fresh cookies corner",
        "trucillo",
        "p.f. chang's",
        "neychor kada",
        "salt",
        "koob al gahwa",
        "tanuki",
        "asiankitchen",
        "bkry",
        "nguyen cimit",
        "miyabi",
        "tashas",
        "desi village",
        "vietnamese",
        "firas al diyafa",
        "manooshe",
        "awani",
        "sultan saray",
        "pincode",
        "commonground",
        "nala",
        "bombay bungalow",
        "punjab by amritsr",
        "the daily",
        "subway",
        "wagamama",
        "caffe nero",
        "fresh and tasty",
        "alkanz lakeshore",
        "cafe bateel",
        "bateel",
        "hutong",
        "asiakitchen",
        "asia kitchen",
        "tbk",
        "smoked meat world",
        "nandos",
        "nando's",
        "kyochon",
        "tarbush",
        "laderach",
        "chagee",
        "chica bonita",
        "saffron & spices",
        "al amar",
        "amici",
        "baan india",
        "ginger farm kitchen",
        "bianca",
        "biancaitalian",
        "plantiful",
        "pacamara",
        "pacamara-qsncc",
        "pacamara-one bangkok",
        "dean and deluca",
        "ohkajhu",
        "getfresh",
        "getfresh-exchange tower",
        "getfresh-samyan mitrtown",
        "getfresh-empire tower",
        "bowlito",
        "james boulangerie",
        "chester's",
        "bonchon",
        "the bibimbab",
        "guljak topokki",
        "dough bros",
        "oakberry acai",
        "wwa",
        "w w a",
        "shaloba",
        "jharoka",
        "ghljharoka",
        "ksher akaraskyroofto",
        "akaraskyrooftobangkok",
        "royce",
        "godiva",
        "benlai one bangkok",
        "piri piri flaming grill",
        "naixue",
        "bn-icon siam",
        "pf changs",
        "p f changs",
        "al shayapf changs",
        "docg",
        "dark-emquartier",
        "chuan kitchen",
        "heytea",
        "jasons deli",
        "paris baguette",
        "pezzo",
        "origin+bloom",
        "origin and bloom",
        "punjab grill",
        "shaans north indian",
        "shaan north indian",
        "sanchos paragon",
        "sanchos",
        "mitsukoshi depachika",
        "oriental gourmet",
        "the oriental gourmet",
        "bosporus",
        "leto",
        "google nomadtable",
        "google tantan asian",
        "google viki asian dra",
        "alsafadi",
        "alsafadi restaurant",
        "awfully chocolate",
        "boon coffee",
        "cafe bateel",
        "cafebateel",
        "cafobateel",
        "coffee club",
        "commonground",
        "cps coffee",
        "french spirit coffee",
        "hashmi bhatti",
        "hili coffee house",
        "i coffee",
        "kcal",
        "line man",
        "mado",
        "masala xpress",
        "mcdonald's",
        "muin sukhumvit 63",
        "nua tair",
        "origin+bloom",
        "pescado seafood grill",
        "piri piri flaming gril",
        "pincode",
        "roasters coffee house",
        "salkara",
        "the coffee lab",
        "top cafeteria",
        "bosporus sharjah",
        "uber eats"
    )

    private val GROCERY = setOf(
        "bigbasket",
        "blinkit",
        "zepto",
        "grofers",
        "jiomart",
        "dmart",
        "reliance fresh",
        "more",
        "grocery",
        "dunzo",
        "careem groceries",
        "careem quik",
        "carrefour",
        "spinneys",
        "lulu",
        "choithrams",
        "waitrose",
        "geant",
        "union coop",
        "abu dhabi co-op",
        "emirates cooperative",
        "nesto",
        "almaya",
        "rawabi",
        "safeer",
        "hippo box",
        "247 corner",
        "new era super market",
        "baqala",
        "lebanese fruit co",
        "al tayeb meat",
        "west zone fresh",
        "majid al futtaim hypermarket",
        "all day mini",
        "all day plus",
        "fresh good day",
        "al ghabat city",
        "zoom",
        "zoom site",
        "all day",
        "all day advantage mini",
        "noon minutes",
        "crrefour",
        "maf mkt",
        "jaya grocer",
        "jaya grocer-intermark",
        "villa market",
        "villa market-gaysorn",
        "villa market-lang suan",
        "gourmet market",
        "gourmet market emporium",
        "tops",
        "tops-central world",
        "mini big c",
        "mini big c-soi prachum",
        "7-11",
        "7-11 sukhumvit22",
        "7-11 one bangkok",
        "7-11 icon siam",
        "7-11 park venture",
        "7-11 maneeya chitlom",
        "donki",
        "donki mall",
        "donki mall thonglor",
        "guardian",
        "guardian paragon",
        "craft minimart",
        "foodland",
        "luluhypermarket",
        "majid al futtaim hypmk",
        "majid al futtaim hypm",
        "keells",
        "glomark",
        "spar"
    )

    private val TRANSPORT = setOf(
        "uber", "ola", "rapido", "metro", "irctc", "redbus", "makemytrip",
        "goibibo", "petrol", "fuel", "parking", "toll", "fastag",
        "indigo", "air india", "spicejet", "vistara", "cleartrip",
        "careem ride", "careem hala ride", "yango",
        "www.grab.com",
        "grab rides",
        "pyxbolt services",
        "bolt services",
        "emarat", "adnoc", "enoc", "epc", "dolphin energy",
        "careem",
        "farid car park",
        "big boss rent a car",
        "presidential transport",
        "q mobility",
        "valtrans",
        "eppco", "eppco site", "eppco-site", "tasjeel", "integrated transport",
        "grab-ec", "grabtaxi", "bolt", "mrt-bem", "airports of thailand",
        "sri rat expressway", "chalerm maha nakhon expressway", "expressway",
        "opntrueiservicetopup", "opn true iservice topup",
        "shell", "shell 0071f", "petaling jaya grab",
        "opvn bike tour",
        "acv noi bai",
        "noi bai",
        "grab a-",
        "grab 5-",
        "sats",
        "sats t1",
        "sats t1i4",
        "vnpay",
        "vnpaytram",
        "chalerm maha nakhon ex",
        "expressway",
        "point sbia",
        "ptt",
        "pttst.c",
        "smart auto",
        "interchange",
        "pickme"
    )

    private val SHOPPING = setOf(
        "amazon", "flipkart", "myntra", "ajio", "nykaa", "meesho",
        "snapdeal", "shopclues", "firstcry", "pepperfry", "urban ladder",
        "store", "mart"
    )
    private val SHOPPING_EXCLUDE = setOf("jiomart", "dmart")

    private val SHOPPING_EXTENDED = setOf(
        "paypal",
        "gmg consumer",
        "bloomingdales",
        "dubizzle",
        "veda inc investment",
        "al futtaim trading",
        "tipr tech",
        "jumbo electronics",
        "shake shack",
        "home centre",
        "qissat al oud",
        "citywalk retail",
        "ova accessories",
        "the sport shack",
        "dubai duty free",
        "level shoes",
        "balmain",
        "zara",
        "daikan",
        "king koil",
        "asas auto accessories",
        "easy blinds",
        "dubai furniture",
        "whsmith",
        "brands for less",
        "sharaf dg",
        "american eagle",
        "dufry",
        "a j a international",
        "aja international",
        "noon e-commerce",
        "noon",
        "m h al shaya",
        "beside trading",
        "intelligent oud",
        "qissat aloud perfumes",
        "uniqlo",
        "uniqlo trx",
        "h&m",
        "sephora",
        "louis vuitton",
        "gucci",
        "chanel",
        "prada",
        "tiffany & co",
        "burberry",
        "hermes",
        "cartier",
        "dior",
        "fendi",
        "versace",
        "michael kors",
        "coach",
        "tory burch",
        "ralph lauren",
        "armani",
        "adidas",
        "nike",
        "puma",
        "reebok",
        "under armour",
        "lululemon",
        "the north face",
        "godiva pavilion",
        "skechers",
        "urban revivo",
        "owndays",
        "it city",
        "it city centralworld",
        "crc sports",
        "sony (central world)",
        "apple central world",
        "lazada limited",
        "www.2c2p.comlazada",
        "2c2p lazada",
        "www.2c2p.com lazada",
        "sephora (thailand)",
        "eveandboy",
        "eveandboy/gaysorn",
        "istudio",
        "istudio-siam paragon",
        "wh smith singapore",
        "lyn",
        "fiverr",
        "select media",
        "adobe",
        "adobe.com",
        "lastpass",
        "lastpass.com",
        "openai chatgpt",
        "openai",
        "cursor",
        "cursor usage",
        "docg pte ltd",
        "blu intelligent solutions",
        "gajeto-23",
        "sukhumvit city mall",
        "the emsphere",
        "central world",
        "emquartier",
        "iconsiam",
        "central worl",
        "angelic aroma",
        "blu intelligent solut",
        "lril",
        "siam paragon dept",
        "siam paragon sup",
        "smartordering",
        "smartordering technolo",
        "space hub general ware",
        "virgin megastore",
        "empire tower",
        "the empire tower",
        "aliexpress",
        "arpico",
        "nolimit",
        "lady j"
    )

    private val UTILITIES = setOf(
        "electricity",
        "water",
        "gas",
        "broadband",
        "wifi",
        "internet",
        "tata sky",
        "dish",
        "d2h",
        "bill",
        "tata power",
        "adani",
        "bses",
        "act fibernet",
        "sdgdubaipay",
        "careem plus",
        "noqejari",
        "saya",
        "aljada developments",
        "nshama",
        "tasleem",
        "tasleem address harbour",
        "greenland environment",
        "noq south energy",
        "noqsouth energy dwc",
        "tamdeed projects",
        "smart dubai government",
        "paysolut",
        "ceypetco",
        "mobitel",
        "slt",
        "dialog axiata"
    )

    private val ENTERTAINMENT = setOf(
        "netflix", "spotify", "prime", "hotstar", "sony liv", "zee5",
        "voot", "youtube", "cinema", "pvr", "inox", "bookmyshow",
        "gaana", "jiosaavn", "apple music", "wynk",
        "global village",
        "major cineplex",
        "www.majorcineplex.com",
        "2c2pmajor cineplex",
        "2c2p major cineplex",
        "major 1066",
        "major 1126",
        "ticketmelon",
        "www.2c2p ticketmelon",
        "www.2cticketmelon",
        "sfcinemacity",
        "platinumlist.net",
        "scope entertainment",
        "scope cinemas"
    )

    private val HEALTHCARE = setOf(
        "1mg", "pharmeasy", "netmeds", "apollo", "pharmacy", "medical",
        "hospital", "clinic", "doctor", "practo", "healthkart", "truemeds",
        "ascent e n t",
        "watson",
        "dr nutrition",
        "boots",
        "supercare",
        "life pharmacy",
        "life phy",
        "life pharm",
        "deira life pharm",
        "medex",
        "bumrungrad",
        "watsons",
        "lac nutrition for life",
        "mediclinic al sufouh",
        "boots_",
        "boots_4287 c.world 3 fbangkok th",
        "healthcare",
        "medihelp",
        "union chemists"
    )

    private val INVESTMENT = setOf(
        "groww", "zerodha", "upstox", "kuvera", "paytm money", "coin",
        "smallcase", "mutual fund", "sip", "angel", "5paisa", "etmoney"
    )

    private val BANKING = setOf(
        "hdfc", "icici", "axis", "sbi", "kotak", "bank", "loan", "emi",
        "credit card", "yes bank", "idfc", "indusind", "pnb", "canara", "union bank", "rbl",
        "atm withdrawal",
        "bank transfer",
        "bank account operation",
        "bank cheque operation",
        "bank cash operation",
        "my fatoorah",
        "cash withdrawal",
        "cash deposit",
        "refund",
        "outward remittance",
        "inward remittance",
        "transfer to",
        "transfer from",
        "transfer: "
    )

    private val PERSONAL_CARE = setOf(
        "urban company", "salon", "spa", "barber", "beauty", "grooming", "housejoy",
        "green belt cleaning",
        "magic washer laundry",
        "stile di capelli",
        "q2 general cleaning",
        "ahmed sammie",
        "clean car washers",
        "italiano style men",
        "high level car wash",
        "home care",
        "final touch cleaning",
        "drip n dry",
        "careem homeservices",
        "skin iii",
        "truefitt and hill",
        "sultans of shave",
        "mandarin oriental spa",
        "black amber sathorn",
        "o.c.c.black amber sathorn",
        "easy way laundry",
        "splice barbershop",
        "mandarin oriental spa",
        "o.c.c.black amber sath",
        "o.c.c.public co.,ltd",
        "phetsathorn"
    )

    private val EDUCATION = setOf(
        "byju", "unacademy", "vedantu", "coursera", "udemy", "upgrade",
        "school", "college", "university", "toppr", "udacity", "simplilearn",
        "whitehat", "great learning"
    )

    private val MOBILE = setOf(
        "airtel", "jio", "vodafone", "idea", "bsnl", "recharge", "prepaid", "postpaid", "mobile",
        "etisalat"
    )

    private val FITNESS = setOf(
        "cult",
        "gym",
        "fitness",
        "yoga",
        "healthifyme",
        "fitternity",
        "gold's gym",
        "anytime fitness"
    )

    private val INSURANCE = setOf(
        "insurance", "lic", "policy", "hdfc life", "icici pru", "sbi life",
        "max life", "bajaj allianz", "policybazaar", "acko", "digit"
    )

    private val TAX = setOf(
        "tin", "tax information", "income tax", "gst", "tax payment", "challan",
        "direct tax", "indirect tax", "tax deducted", "tds", "advance tax", "self assessment",
        "abu dhabi judicial dept",
        "sharjah finance dept",
        "tassheel",
        "dubai courts",
        "ministry of interior",
        "abu dhabi judicial dep",
        "sharjah finance depart",
        "smartdxbgov-ded"
    )

    private val BANK_CHARGE = setOf(
        "recovery", "charge", "fee", "penalty", "maintenance", "non-maintenance",
        "minimum balance", "sms charge", "atm recovery", "service charge",
        "annual fee", "processing fee", "convenience fee", "late payment",
        "cheque returned"
    )

    private val CC_PAYMENT = setOf(
        "bbps", "bill payment", "credit card payment", "cc payment", "card payment"
    )

    private val TRAVEL = setOf(
        "make my trip",
        "yatra",
        "ixigo",
        "booking.com",
        "expedia",
        "agoda",
        "trip.com",
        "trivago",
        "hotels.com",
        "kayak",
        "travelocity",
        "airbnb",
        "vrbo",
        "skyscanner",
        "momondo",
        "tripadvisor",
        "w bangkok",
        "bangkok marriott",
        "flight",
        "airline",
        "hotel",
        "marriott",
        "hyatt",
        "hilton",
        "accor",
        "taj",
        "oberoi",
        "itc hotels",
        "leela",
        "jumeirah",
        "address hotels",
        "address grand",
        "palace downtown",
        "burj al arab",
        "one&only",
        "five luxe",
        "five palm jumeirah",
        "atlantis the palm",
        "atlantis the royal",
        "anantara the palm",
        "vida downtown",
        "vida dubai creek",
        "vida emirates hills",
        "emirates palace",
        "radisson",
        "sheraton",
        "westin",
        "ritz carlton",
        "four seasons",
        "conrad",
        "st regis",
        "jw marriott",
        "grand hyatt",
        "le meridien",
        "waldorf astoria",
        "intercontinental",
        "fairfield",
        "holiday inn express",
        "hampton by hilton",
        "doubletree by hilton",
        "courtyard by marriott",
        "residence inn",
        "homewood suites",
        "aloft",
        "element by westin",
        "the edition",
        "tribe living",
        "s/o uptown",
        "moxy",
        "four points by sherato",
        "doubletree",
        "holiday inn",
        "novotel",
        "mercure",
        "ibis",
        "fairmont",
        "sofitel",
        "pullman",
        "movenpick",
        "citadines",
        "oyo",
        "treebo",
        "fabhotels",
        "signiel",
        "aman",
        "aman resorts",
        "anantara",
        "banyan tree",
        "six senses",
        "rosewood",
        "capella",
        "kempinski",
        "kimpton maa-lai",
        "the ritz-carlton reserve",
        "ryanair",
        "lufthansa",
        "emirates",
        "qatar airways",
        "british airways",
        "air france",
        "klm",
        "singapore airlines",
        "etihad airways",
        "turkish airlines",
        "cathay pacific",
        "ana",
        "alaska airlines",
        "hawaiian airlines",
        "southwest airlines",
        "jetblue",
        "allegiant air",
        "spirit airlines",
        "vfs global",
        "dubai world trade centre",
        "dubai world trade cent",
        "vfs uk",
        "vfs world trade centre",
        "vfs wtc",
        "address downtown",
        "the address downtown",
        "the meydan",
        "crowne plaza",
        "crowne plaza klcc",
        "four points by sheraton",
        "sindhorn kempinski",
        "st.regis bangkok",
        "the st.regis bangkok",
        "dusit thani bangkok",
        "staybridge",
        "park silom",
        "the parq",
        "marina bay sands",
        "mbs front office",
        "w singapore",
        "gardens by the bay",
        "gardens by the bay-ret",
        "gardens by the bay-tic",
        "king power mahanakhon",
        "al reyadah hospitality",
        "four points by sheraton",
        "king group hospitality",
        "magnolias serviced",
        "magnoliasservicedrbangkok"
    )

    // --- single ordered rule list (priority preserved) ---
    private data class Rule(
        val categoryName: String,
        val includes: Set<String>,
        val excludes: Set<String> = emptySet()
    )

    private val RULES: List<Rule> = listOf(
        Rule("Tax", TAX),
        Rule("Bank Charges", BANK_CHARGE),
        Rule("Credit Card Payment", CC_PAYMENT),
        Rule("Food & Dining", FOOD),
        Rule("Groceries", GROCERY),
        Rule("Transportation", TRANSPORT),
        Rule("Shopping", SHOPPING + SHOPPING_EXTENDED, SHOPPING_EXCLUDE),
        Rule("Bills & Utilities", UTILITIES),
        Rule("Entertainment", ENTERTAINMENT),
        Rule("Healthcare", HEALTHCARE),
        Rule("Investments", INVESTMENT),
        Rule("Banking", BANKING),
        Rule("Personal Care", PERSONAL_CARE),
        Rule("Education", EDUCATION),
        Rule("Mobile", MOBILE),
        Rule("Fitness", FITNESS),
        Rule("Insurance", INSURANCE),
        Rule("Travel", TRAVEL),
    )

    /**
     * Get category for a merchant name (expense-only lookup).
     */
    fun getCategory(merchantName: String): String {
        val merchantLower = merchantName.lowercase()
        for (rule in RULES) {
            if (matches(merchantLower, rule.includes, rule.excludes)) {
                return rule.categoryName
            }
        }
        return "Others"
    }

    /**
     * Determines the category based on merchant name and transaction type.
     * Handles income-specific logic (salary, refund, cashback, interest, dividend).
     */
    fun determineCategory(merchantName: String, transactionType: String): String {
        if (transactionType == "INCOME") {
            val merchantLower = merchantName.lowercase()
            return when {
                merchantLower.contains("salary") -> "Salary"
                merchantLower.contains("refund") -> "Refunds"
                merchantLower.contains("cashback") -> "Cashback"
                merchantLower.contains("interest") -> "Interest"
                merchantLower.contains("dividend") -> "Dividends"
                else -> "Income"
            }
        }

        return getCategory(merchantName)
    }
}
