package com.example

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * The supported-banks catalogue, loaded once at startup from the classpath.
 *
 * `supported-banks.json` is GENERATED from the live `BankParserFactory` registry by
 * parser-core's `SupportedBanksDocTest` (run `scripts/update-supported-banks.sh`), which
 * writes both `docs/supported-banks.json` and this module's resource copy and fails CI if
 * either drifts. So every bank/country page below is guaranteed to describe a parser that
 * actually exists — we can never publish a page for a bank we don't support.
 */
@Serializable
data class BankCatalogue(
    val totalBanks: Int,
    val totalCountries: Int,
    val countries: List<CountryEntry>,
)

/**
 * A real sample message for one bank plus what the live parser extracted from it.
 * Generated by parser-core's `BankSamplesDocTest`, so both halves are genuine — the
 * landing pages can't demo an extraction the app wouldn't actually make.
 */
@Serializable
data class BankSample(
    val sender: String,
    val message: String,
    val currency: String,
    val amount: String,
    val type: String,
    val merchant: String? = null,
    val accountLast4: String? = null,
    val reference: String? = null,
    val balance: String? = null,
)

@Serializable
private data class BankSampleFile(val samples: Map<String, BankSample> = emptyMap())

@Serializable
data class CountryEntry(
    val country: String,
    val flag: String,
    val currency: String,
    val symbol: String,
    val bankCount: Int,
    val banks: List<String>,
)

/** A single bank, flattened with its country context — what a `/banks/{slug}` page renders. */
data class BankPage(
    val name: String,
    val slug: String,
    val country: CountryEntry,
)

object SupportedBanks {

    private val json = Json { ignoreUnknownKeys = true }

    val catalogue: BankCatalogue by lazy {
        val stream = SupportedBanks::class.java.getResourceAsStream("/supported-banks.json")
            ?: error(
                "supported-banks.json missing from the server resources — " +
                    "run scripts/update-supported-banks.sh"
            )
        stream.bufferedReader().use { json.decodeFromString<BankCatalogue>(it.readText()) }
    }

    /** Country slug, e.g. "United States" -> "united-states". */
    fun countrySlug(country: String) = slugify(country)

    val countries: List<CountryEntry> get() = catalogue.countries

    /** Every bank, flattened. Sorted by name so the index and sitemap are stable. */
    val banks: List<BankPage> by lazy {
        val flattened = catalogue.countries.flatMap { country ->
            country.banks.map { BankPage(name = it, slug = slugify(it), country = country) }
        }.sortedBy { it.name }

        // Two banks slugging to the same URL would silently shadow one another, so fail
        // loudly at startup rather than serving the wrong page.
        val collisions = flattened.groupBy { it.slug }.filterValues { it.size > 1 }
        check(collisions.isEmpty()) {
            "Bank slug collision(s): " + collisions.entries.joinToString("; ") { (slug, pages) ->
                "$slug <- ${pages.joinToString(", ") { it.name }}"
            }
        }
        flattened
    }

    private val bySlug: Map<String, BankPage> by lazy { banks.associateBy { it.slug } }
    private val countryBySlug: Map<String, CountryEntry> by lazy {
        // Same hazard as bank slugs: two country names slugging to one URL would
        // silently shadow each other under associateBy, serving the wrong page.
        val collisions = catalogue.countries.groupBy { countrySlug(it.country) }.filterValues { it.size > 1 }
        check(collisions.isEmpty()) {
            "Country slug collision(s): " + collisions.entries.joinToString("; ") { (slug, entries) ->
                "$slug <- ${entries.joinToString(", ") { it.country }}"
            }
        }
        catalogue.countries.associateBy { countrySlug(it.country) }
    }

    /**
     * Live parse demos, keyed by bank name. Not every bank has one — a bank only appears
     * here if the test corpus contains a message its parser handles cleanly — so callers
     * must degrade gracefully rather than assume a hit.
     */
    private val samples: Map<String, BankSample> by lazy {
        val stream = SupportedBanks::class.java.getResourceAsStream("/bank-samples.json")
            ?: return@lazy emptyMap()
        stream.bufferedReader().use { json.decodeFromString<BankSampleFile>(it.readText()).samples }
    }

    fun sample(bankName: String): BankSample? = samples[bankName]

    fun bank(slug: String): BankPage? = bySlug[slug.lowercase()]

    fun country(slug: String): CountryEntry? = countryBySlug[slug.lowercase()]

    private fun slugify(value: String): String = value
        .lowercase()
        .map { if (it.isLetterOrDigit()) it else '-' }
        .joinToString("")
        .split('-')
        .filter { it.isNotEmpty() }
        .joinToString("-")
}
